package com.example.demo.persistence;
/**
 * persistent entity ORM of table  TBL_DEMO_ARRAY  
 */
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;


@Data
@Getter @Setter
@EqualsAndHashCode 
@Entity
@Table(name="TBL_DEMO_ARRAY")
public class DemoArray {
 
   /*
    * unique id generated by hashcode builder as per input array 	
    */
   @Id
   private Integer id;
     
   /*
    *Jason array which holds array numbers 	
    */

    @Column(name="numbers")  
    @Lob
    private String numbers;
     
}
